### ISSUE TITLE
Error: Cannot find module swaglanguagepack/src/Resources/app/administration/build/webpack.config.js

### ISSUE THREAD

**Issue by carstenjaksch** [shopware/platform#7200]
*PHP Version:* 8.3   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Extension:Language-Extensions 

 ----

*_Actual behaviour:_*

After updating `swaglanguagepack` from 4.26.0 to 4.28.0 via Composer, the following error occurs during build process:

![Image](https://github.com/user-attachments/assets/d9d00956-2596-48fc-983b-109517402bf5)

Downgrading to 4.26.0 fixed the issue.

We use Deployer with GitHub Actions for the build process. The following command is used to build:

```
CI=1 SHOPWARE_SKIP_THEME_COMPILE=1 SHOPWARE_SKIP_BUNDLE_DUMP=1 SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1 DISABLE_ADMIN_COMPILATION_TYPECHECK=1 ADMIN_WORKER=0 ./bin/build-js.sh
```

*_Expected behaviour:_*

Successful deploy.

*_How to reproduce:_*

1. Install Shopware 6.6.9.0
2. Install swaglanguagepack 4.28.0 via Composer.
3. Try to deploy without a database.

**Comment by shopwareBot** [comment]
[public] Shopware automated response: This issue is linked to the internal issue: **LAN-193**



[created from LAN-193, comment 542650]

**Comment by shopwareBot** [comment]
[public] 

 > Priority changed to: **High**

 Thank you for your report. Based on the information in this report, we have decided to investigate this issue in more detail and are planning to provide a fix for this issue. Although we are always eager to solve such problems as soon as we can, we can't give you a more specific time frame right now. We appreciate your patience and thank you for your understanding.



[created from LAN-193, comment 543226]

**Comment by bschulzebaek** [comment]
Hey @carstenjaksch , thanks for bringing up this issue 👋🏻 

For context: The LanguagePack was extending the admin webpack config to add some custom file type handling, which wasn't  actually used in a while, so we removed the config file. Additionally, from Shopware 6.7 on, we wouldn't even need such an extension because of the transition to Vite as our build tool.

While the removal of the webpack config extension shouldn't cause any issues with our admin build system (if no file existst, we don't attempt to load it), my assumption is that there's an outdated `var/plugin.json` file (see the screenshot) or some kind of Webpack cache in your pipeline. Do you mind to double-check or provide some more context (for example an actual GH action file with a minimal reproduction)?

![var/plugins.json](https://github.com/user-attachments/assets/02afd056-1027-42d5-90ca-8ab884c0ac85)

**Comment by marcelbrode** [comment]
Since we noticed no activities in the last 5 months, I'll close this ticket. Feel free to ping us, if you've have additional information, we will gladly reopen this ticket. Thank you :smile:
